#include <iostream>
#include <map>

int main() {
    int n;
    std::cin >> n;
    
    std::map<int, int> freq_map;
    
    for (int i = 0; i < n; ++i) {
        int num;
        std::cin >> num;
        freq_map[num]++;
    }
    
    auto it = freq_map.begin();
    if (it != freq_map.end()) {
        std::cout << it->first;
        ++it;
        for (; it != freq_map.end(); ++it) {
            std::cout << " " << it->first;
        }
    }
    std::cout << "\n";
    
    it = freq_map.begin();
    if (it != freq_map.end()) {
        std::cout << it->second;
        ++it;
        for (; it != freq_map.end(); ++it) {
            std::cout << " " << it->second;
        }
    }
}

{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: g++.exe build active file",
            "command": "C:\\msys64\\ucrt64\\bin\\g++.exe",
            "args": [
                "-fdiagnostics-color=always",
                "-g",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"
}